/// Flutter icons SmartMirrorApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SmartMirrorApp
///      fonts:
///       - asset: fonts/SmartMirrorApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SmartMirrorApp {
  SmartMirrorApp._();

  static const _kFontFam = 'SmartMirrorApp';
  static const String _kFontPkg = null;

  static const IconData bottom = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData top = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData middle = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
